stages:
  common-prepare-train-data:
    cmd: >
      credit-risk common-prepare-train-data
      --input-path data/raw/cs-training.csv
      --output-path data/interim/train_prepared.csv
    deps:
      - data/raw/cs-training.csv
      - src/credit_risk_scoring/preprocessing/common_prepare_data.py
      - src/credit_risk_scoring/preprocessing/commands.py
    outs:
      - data/interim/train_prepared.csv

  common-prepare-test-data:
    cmd: >
      credit-risk common-prepare-test-data
      --input-path data/raw/cs-test.csv
      --output-path data/interim/test_prepared.csv
    deps:
      - data/raw/cs-test.csv
      - src/credit_risk_scoring/preprocessing/common_prepare_data.py
      - src/credit_risk_scoring/preprocessing/commands.py
    outs:
      - data/interim/test_prepared.csv

  build-feature-engineering-datasets:
    cmd: >
      credit-risk build-feature-engineering-datasets
      --train-input-path data/interim/train_prepared.csv
      --test-input-path data/interim/test_prepared.csv
      --linear-train-output-path data/processed/linear/train.csv
      --linear-test-output-path data/processed/linear/test.csv
      --tree-train-output-path data/processed/tree/train.csv
      --tree-test-output-path data/processed/tree/test.csv
    deps:
      - data/interim/train_prepared.csv
      - data/interim/test_prepared.csv
      - src/credit_risk_scoring/cli.py
      - src/credit_risk_scoring/preprocessing/commands.py
      - src/credit_risk_scoring/preprocessing/feature_engineering.py
    outs:
      - data/processed/linear/train.csv
      - data/processed/linear/test.csv
      - data/processed/tree/train.csv
      - data/processed/tree/test.csv
